title:            Bazinga
description:      Bazinga's home page on the World Wide Web.
url:              https://site.bazinga.ink
lang:              en-US

# SEO配置
author:
  name:           Bazinga
  email:          zhangyouxiu66@gmail.com

# 网站关键字
keywords:         bazinga, blog, personal website, notes, stories, photos, travel, life

# 社交媒体链接
social:
  github:         https://github.com/BazingaOrg
  twitter:        https://x.com/zhangyouxiu6

# 网站图标和图片
favicon:          /assets/favicon-32x32.png
logo:             /assets/logo.png
permalink:        /posts/:title
timezone:         Asia/Shanghai
sass:
  sass_dir: assets
  style: :compressed
collections:
  posts:
    output: true
  notes:
    output: true
    permalink: /notes/:name/
  pages:
    output: true
    permalink: /:name/
  stories:
    output: true
    permalink: /stories/:name/
i18n:
  en-US:
    accessibility: Accessibility statement
    source: View source
  zh-CN:
    Travel: 旅行
    Animals: 动物
    Taiwan: 台湾
    Books: 书籍
    Cook: 厨房
    Plants: 植物
    24h: 24h
    Mails: 邮件
    Friends: 朋友
    Oven: 烤箱
    Self: 本人
    Polaroid: 拍立得
    Chat: 对话
    Meow: 喵咪
    Hobby: 兴趣
    accessibility: 无障碍说明
    source: 查看源码
include: [".well-known"]
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "HARDBREAKS"]
  extensions: ["strikethrough", "autolink", "table"]
recent_date: "2025/07/30"
