name: "Upload story"

on:
  workflow_dispatch:
    inputs:
      filepath:
        description: "JSON file path for the data"
        type: string
        required: true
      filedata:
        description: "Stringify JSON data of the story"
        type: string
        required: true
concurrency: ci-${{ github.action }}

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version: 17.7

      - name: Run script
        run: node .github/workflows/scripts/story.js '${{ inputs.filepath }}' '${{ inputs.filedata }}'

      - name: Push changes
        run: |
          git config user.email 'bot@muan.dev'
          git config user.name 'muan [bot]'
          git add .
          git commit -m "Add photo from Apple shortcuts" || echo "Nothing to commit"
          git fetch origin main
          git push origin HEAD:main
