name: "Fetch and save robots.txt"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 * * *' # * 16:00 UTC +08:00

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push changes
        run: |
          curl https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/robots.txt > robot.txt
          git config user.email "bot@muan.dev"
          git config user.name "guardian [bot]"
          git add .
          git commit -m "Update robots.txt" || echo "Nothing changed in ai-robots-txt.txt"
          git fetch origin main
          git push origin HEAD:main
